Python 3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> services:
...   - type: worker
...     name: capitan
...     env: python
...     buildCommand: "pip install -r requirements.txt"
...     startCommand: "python main.py"
